apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-echo
  labels:
    app: demo-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-echo
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "demo-echo"
        dapr.io/config: demo-echo
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "50051"
      labels:
        app: demo-echo
    spec:
      containers:
        - name: demo-echo
          image: tkeelio/echo-demo:0.0.1 # EDIT HERE: Replace the image name
          imagePullPolicy: Always
          command:
            - "python"
          args:
            - "/app/demo-echo.py"
          ports:
            - containerPort: 3000
          env:
            - name: KEEL_PRIVATE_STORE
              value: "0"