# > tkeel platform values
# default plugin id
daprConfig: keel
# < tkeel platform values

# plugin custom values
middleware:
  name: tkeel-middleware
replicaCount: 1
nodePort: 30707
image:
  repository: tkeelio/keel
  tag: v0.3.0
  pullPolicy: Always

# keel debug mod
debug: false

# keel log level
logLevel: debug

# keel http port and dapr app port
httpPort: 32134

# keel grpc port
grpcPort: 32133

# keel goroutine watch interval
watchInterval: 1s

# dapr component
dapr:
  state:
    publicName: tkeel-middleware-redis-public-store
