apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: rudder
  namespace: keel-system
spec:
  accessControl:
    defaultAction: deny
    trustDomain: "keel"
    policies:
      - appId: rudder
        defaultAction: allow
        trustDomain: "keel"
        namespace: "keel-system"
      - appId: keel
        defaultAction: allow
        trustDomain: "keel"
        namespace: "keel-system"
  httpPipeline:
    handlers:
      - name: rudder-oauth2-client
        type: middleware.http.oauth2clientcredentials
