apiVersion: v1
kind: Service
metadata:
  name: {{ include "core.name" . }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.appPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "core.selectorLabels" . | nindent 4 }}
