# Default values for keel-paas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

redis:
  architecture: standalone
  fullnameOverride: tkeel-middleware-redis
  auth:
    password: Biz0P8Xoup

mysql:
  fullnameOverride: tkeel-middleware-mysql
  auth:
    rootPassword: a3fks=ixmeb82a
    database: tkeelauth
