{{- range tuple $.Values.redisPrivate $.Values.redisPublic }}
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .addr }}
  - name: redisPassword
    secretKeyRef:
      key: redis-password
      name: {{ .passSecret }}
  {{- if (eq .type "public") }}
  - name: keyPrefix
    value: none
  {{- end }}
{{- end }}