apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: keel-system
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "auth"
        dapr.io/app-port: "8080"
        dapr.io/config: auth
    spec:
      imagePullSecrets:
        - name: hub-qingcloud
      containers:
        - name: auth
          image: dockerhub.qingcloud.com/iotpaas/auth:0.0.4
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP