apiVersion: v1
kind: Service
metadata:
  name: {{ include "rudder.name" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: {{ include "rudder.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
      nodePort: {{ .Values.nodePort }}
  type: NodePort