apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: keel-private-store
  namespace: keel-system
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      key: redis-password
      name: redis