apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
  namespace: keel-system
  labels:
    app: keel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keel
  template:
    metadata:
      labels:
        app: keel
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "keel"
        dapr.io/app-port: "31234"
        dapr.io/config: keel
    spec:
      containers:
        - name: keel
          image: tkeelio/keel:0.2.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 31234
              protocol: TCP
