apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: core-state
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: core-redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: core-redis
      key: redis-password

