apiVersion: v1
kind: Service
metadata:
  name: {{ include "keel.name" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: {{ include "keel.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.global.pluginPort }}
      targetPort: {{ .Values.global.pluginPort }}
      nodePort: {{ .Values.nodePort }}
  type: NodePort