global:
  replicaCount: 1
  pluginPort: 8080
  privateStore: tkeel-redis-private-store
  publicStore: tkeel-redis-public-store

daprConfig: keel

imagePullSecrets: ""

nodePort: 30777

image:
  repository: tkeelio/keel
  tag: 0.0.1
  pullPolicy: Always