name: main
on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
jobs:
  check:
    uses: tkeel-io/tkeel/.github/workflows/public_call.yml@main
    with:
      upload_require: false
  upload:
    if: github.event.pull_request.types == 'closed'
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - name: Push image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        uses: tkeel-io/tkeel/.github/workflows/push_image.yml@main
        with:
          dockerhub_name: ${{ env.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ env.DOCKERHUB_PASSWORD }}
