name: push_image
on:
  workflow_call:
    inputs:
      image_tag:
        description: docker image tags
        default: latest
        required: false
        type: string
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  docker:
    name: build and push latest image
    runs-on: ubuntu-latest
    env:
      GOVER: ^1.17.5
    steps:
      - name: Set up Go ${{env.GOVER}}
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ env.GOVER }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run make go.mod check-diff
        run: git diff --exit-code ./go.mod
      - name: Codecov
        uses: codecov/codecov-action@v1
      - name: Run make release
        run: |
          make release GOOS=linux GOARCH=amd64
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_PASSWORD}}
      - name: build dev-container DOCKER_TAG=${{inputs.image_tag}}
        run: make build-dev-container
