name: on release published
on:
  release:
    types: [published]
jobs:
  check:
    uses: tkeel-io/tkeel/.github/workflows/public_call.yml@main
    with:
      archive_outdir: dist/archivers
      go_version: 1.17.3
  upload:
    name: Upload release files
    needs:
      - check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        project:
          - "*"
    steps:
      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: dist/archivers

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["${{ steps.download.outputs.download-path }}/${{ matrix.project }}"]'
  docker:
    name: Upload images
    needs: [check, upload]
    runs-on: ubuntu-latest
    env:
      GOVER: ^1.17.5
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up Go ${{env.GOVER}}
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ env.GOVER }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run make go.mod check-diff
        run: git diff --exit-code ./go.mod
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Codecov
        uses: codecov/codecov-action@v1
      - name: Run make release
        run: |
          make release GOOS=linux GOARCH=amd64
      - name: build dev-container
        run: make build-dev-container DOCKER_TAG=${{ steps.get_version.outputs.VERSION }}
